#!/bin/bash

# GitHub Issues Sync Script for Symfony Expenses Manager
# This script synchronizes GitHub issues with local documentation

set -e  # Exit on any error

# Configuration
REPO="wabior/Symfony_Expenses_Manager"
OUTPUT_FILE="docs/github_context.md"
TEMP_FILE="/tmp/github_issues_$$.json"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Cleanup function
cleanup() {
    if [ -f "$TEMP_FILE" ]; then
        rm -f "$TEMP_FILE"
        log_info "Cleaned up temporary file"
    fi
}

# Set trap for cleanup
trap cleanup EXIT

# Check if GitHub CLI is installed
check_gh_cli() {
    if ! command -v gh &> /dev/null; then
        log_error "GitHub CLI (gh) is not installed."
        echo "Please install it from: https://cli.github.com/"
        echo "Or run: curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg"
        echo "        echo \"deb [arch=\$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main\" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null"
        echo "        sudo apt update && sudo apt install gh"
        exit 1
    fi

    log_success "GitHub CLI found"
}

# Check if user is authenticated
check_auth() {
    if ! gh auth status &> /dev/null; then
        log_warning "Not authenticated with GitHub CLI"
        echo "Please run: gh auth login"
        exit 1
    fi

    log_success "Authenticated with GitHub"
}

# Show current status
show_status() {
    echo
    log_info "Current GitHub Issues Status:"
    echo

    # Count issues by state
    local open_count=$(gh issue list --repo "$REPO" --state open --json number | jq length 2>/dev/null || echo "0")
    local closed_count=$(gh issue list --repo "$REPO" --state closed --json number | jq length 2>/dev/null || echo "0")

    echo "📋 Open issues: $open_count"
    echo "✅ Closed issues: $closed_count"
    echo "📊 Total issues: $((open_count + closed_count))"
    echo

    # Show recent issues
    echo "🔥 Recent Open Issues:"
    gh issue list --repo "$REPO" --state open --limit 5 --json number,title,updatedAt | jq -r '.[] | "  #\(.number) - \(.title) (\(.updatedAt | strptime("%Y-%m-%dT%H:%M:%SZ") | strftime("%Y-%m-%d")))"' 2>/dev/null || echo "  No issues found"
    echo
}

# Sync issues to local file
sync_issues() {
    log_info "Starting GitHub issues synchronization..."

    # Fetch all issues (open and closed)
    log_info "Fetching issues from GitHub..."
    gh issue list --repo "$REPO" --state all --json number,title,labels,milestone,state,createdAt,updatedAt > "$TEMP_FILE"

    if [ ! -s "$TEMP_FILE" ]; then
        log_error "Failed to fetch issues from GitHub"
        return 1
    fi

    log_success "Fetched $(jq length "$TEMP_FILE") issues"

    # Create markdown file
    log_info "Creating markdown documentation..."

    cat > "$OUTPUT_FILE" << 'EOF'
# GitHub Issues Context - Symfony Expenses Manager

This file contains the current state of all GitHub issues for AI context.
Auto-generated by scripts/github_sync.sh

**Last updated:** $(date)
**Repository:** https://github.com/wabior/Symfony_Expenses_Manager

## Issues Summary

EOF

    # Add summary
    local open_count=$(jq '[.[] | select(.state == "OPEN")] | length' "$TEMP_FILE")
    local closed_count=$(jq '[.[] | select(.state == "CLOSED")] | length' "$TEMP_FILE")
    local total_count=$((open_count + closed_count))

    cat >> "$OUTPUT_FILE" << EOF
- **Open Issues:** $open_count
- **Closed Issues:** $closed_count
- **Total Issues:** $total_count

## Open Issues

EOF

    # Add open issues
    jq -r '.[] | select(.state == "OPEN") | "### Issue #\(.number): \(.title)\n\n**State:** \(.state)\n**Milestone:** \(.milestone.title // "None")\n**Labels:** \([.labels[].name] | join(", ") // "None")\n**Created:** \(.createdAt | strptime("%Y-%m-%dT%H:%M:%SZ") | strftime("%Y-%m-%d"))\n**Updated:** \(.updatedAt | strptime("%Y-%m-%dT%H:%M:%SZ") | strftime("%Y-%m-%d"))\n\n---\n"' "$TEMP_FILE" >> "$OUTPUT_FILE"

    # Add closed issues section
    cat >> "$OUTPUT_FILE" << EOF

## Closed Issues

EOF

    # Add closed issues
    jq -r '.[] | select(.state == "CLOSED") | "### Issue #\(.number): \(.title)\n\n**State:** \(.state)\n**Milestone:** \(.milestone.title // "None")\n**Labels:** \([.labels[].name] | join(", ") // "None")\n**Created:** \(.createdAt | strptime("%Y-%m-%dT%H:%M:%SZ") | strftime("%Y-%m-%d"))\n**Updated:** \(.updatedAt | strptime("%Y-%m-%dT%H:%M:%SZ") | strftime("%Y-%m-%d"))\n\n---\n"' "$TEMP_FILE" >> "$OUTPUT_FILE"

    log_success "Markdown file created: $OUTPUT_FILE"
}

# Show usage
show_usage() {
    echo "Usage: $0 [COMMAND]"
    echo
    echo "Commands:"
    echo "  status    Show current GitHub issues status"
    echo "  sync      Sync all issues to local markdown file"
    echo "  help      Show this help message"
    echo
    echo "Examples:"
    echo "  $0 status    # Show current issues status"
    echo "  $0 sync      # Sync issues to docs/github_context.md"
}

# Main logic
main() {
    echo "🔄 GitHub Issues Sync for Symfony Expenses Manager"
    echo "=================================================="
    echo

    case "${1:-help}" in
        "status")
            check_gh_cli
            check_auth
            show_status
            ;;
        "sync")
            check_gh_cli
            check_auth
            show_status
            echo
            read -p "Do you want to sync all issues to local file? (y/N): " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                sync_issues
                log_success "Synchronization completed!"
                echo
                echo "📄 File created: $OUTPUT_FILE"
                echo "🤖 AI can now read current GitHub issues from this file"
            else
                log_info "Sync cancelled"
            fi
            ;;
        "help"|*)
            show_usage
            ;;
    esac
}

# Run main function
main "$@"
